# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#cfd8dc"

# Title color for boxes
theme[title]="#ff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#90"

# Background color of selected item in processes box
# #ffe4eb
theme[selected_bg]="#ffa6bd"

# Foreground color of selected item in processes box
theme[selected_fg]="#ff"

# Color of inactive/disabled text
theme[inactive_fg]="#40"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#55bcea"

# Cpu box outline color
theme[cpu_box]="#ffe4eb"

# Memory/disks box outline color
theme[mem_box]="#ffe4eb"

# Net up/down box outline color
theme[net_box]="#ffe4eb"

# Processes box outline color
theme[proc_box]="#ffe4eb"

# Box divider line and small boxes line color
theme[div_line]="#50"

# Temperature graph colors
theme[temp_start]="#ffe4eb"
theme[temp_mid]="#ff91ae"
theme[temp_end]="#ff3d6f"

# CPU graph colors
theme[cpu_start]="#ffe4eb"
theme[cpu_mid]="#ff91ae"
theme[cpu_end]="#ff3d6f"

# Mem/Disk free meter
theme[free_start]="#ffe4eb"
theme[free_mid]="#ff91ae"
theme[free_end]="#ff3d6f"

# Mem/Disk cached meter
theme[cached_start]="#ffe4eb"
theme[cached_mid]="#ff91ae"
theme[cached_end]="#ff3d6f"

# Mem/Disk available meter
theme[available_start]="#ff3d6f"
theme[available_mid]="#ff91ae"
theme[available_end]="#ffe4eb"

# Mem/Disk used meter
theme[used_start]="#ff0040"
theme[used_mid]="#ff91ae"
theme[used_end]="#ff3d6f"

# Download graph colors
theme[download_start]="#ffe4eb"
theme[download_mid]="#ff91ae"
theme[download_end]="#ff3d6f"

# Upload graph colors
theme[upload_start]="#ffe4eb"
theme[upload_mid]="#ff91ae"
theme[upload_end]="#ff3d6f"
